Python/django/belt_reviewer/apps/booksApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/$', views.books, name='books'),
    url(r'^add/$', views.add, name='add'),
    url(r'^addBook/$', views.addBook, name='addBook'),
    url(r'^books/(?P<id>\d+)$', views.bookReview, name='bookReview'),
    url(r'^addReview/(?P<id>\d+)$', views.addReview, name='addReview'),
    url(r'^user/(?P<id>\d+)$', views.user, name='user'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete')
]

Python/django/belt_reviewer/apps/logRegApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^log_reg/$', views.log_reg, name='log_reg'),
    url(r'^logout/$', views.logout, name='logout'),
]

Python/django/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.booksApp.urls', namespace='booksApp')),
    url(r'^logRegApp/', include('apps.logRegApp.urls', namespace='logRegApp')),
    # url(r'^admin/', admin.site.urls),
]

Python/django/belt_reviewer/apps/booksApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..logRegApp.models import Users

# Create your models here.
class AuthorsDBManager(models.Manager):
    def get_all_authors(self):
        return AuthorsDB.objects.all()
    def create_author(self, data, user_id):
        print 'Create Author'
        unique = AuthorsDB.objects.filter(name=data['add_author'])
        if unique:
            return [False, 'Author ' + data['add_author'] + 'already exists. Choose them from the dropdown menu']
        AuthorsDB.objects.create(name=data['add_author'], users=Users.objects.get(id=user_id))
        return [AuthorsDB.objects.get(name=data['add_author'])]
    def get_author(self, data):
        return [AuthorsDB.objects.get(name=data['existing_author'])]

class BooksDBManager(models.Manager):
    def create_book(self, data, author_id, user_id):
        if BooksDB.objects.filter(title=data['title']):
            return [False, 'Book ' + data['title'] + ' already exists']
        BooksDB.objects.create(title=data['title'], author=AuthorsDB.objects.get(id=author_id), user=Users.objects.get(id=user_id))
        return [BooksDB.objects.get(title=data['title'])]
    def get_all_books(self):
        return BooksDB.objects.all()

class ReviewsDBManager(models.Manager):
    def create_review(self, data, book_id, user_id):
        ReviewsDB.objects.create(review=data['review'], rating=int(data['rating']), book=BooksDB.objects.get(id=book_id), user=Users.objects.get(id=user_id))


class AuthorsDB(models.Model):
    name = models.CharField(max_length=100)
    users = models.ForeignKey(Users, related_name='users_authors')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = AuthorsDBManager()

class BooksDB(models.Model):
    title = models.TextField()
    author = models.ForeignKey(AuthorsDB, related_name='authors_books', on_delete=models.CASCADE)
    user = models.ForeignKey(Users, related_name='users_books')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BooksDBManager()

class ReviewsDB(models.Model):
    review = models.TextField()
    rating = models.IntegerField()
    book = models.ForeignKey(BooksDB, related_name='books_reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(Users, related_name='users_reviews', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ReviewsDBManager()

# class Ratings(models.Model):
#     rating = models.IntegerField()
#     review = models.OneToOneField(Reviews, related_name='reviews_ratings', on_delete=models.CASCADE)
#     book = models.ForeignKey(Books, related_name='books_ratings', on_delete=models.CASCADE)
#     user = models.ForeignKey(Users, related_name='users_ratings', on_delete=models.CASCADE)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

Python/django/belt_reviewer/apps/booksApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.shortcuts import render, redirect
from ..logRegApp.models import Users
from .models import AuthorsDB, BooksDB, ReviewsDB

# Create your views here.
def index(request):
    print 'Books APP index'
    return render(request, 'booksApp/index.html')

def books(request):
    print 'Books APP Books'
    if 'id' not in request.session:
        return redirect('booksApp:index')
    context = {
        'reviews': ReviewsDB.objects.all()
    }
    return render(request, 'booksApp/books.html', context)

def add(request):
    if 'id' not in request.session:
        return redirect('booksApp:index')
    context = {
        'authors': AuthorsDB.objects.all()
    }
    return render(request, 'booksApp/addBook.html', context)

def addBook(request):
    if request.method == 'POST':
        if request.POST['add_author'] != '':
            print 'Add Author'
            response = AuthorsDB.objects.create_author(request.POST, request.session['id'])
            if not response[0]:
                messages.error(request, response[1])
                return redirect('booksApp:add')
        elif request.POST['existing_author'] != 'choose':
            print 'Existing Author'
            response = AuthorsDB.objects.get_author(request.POST)
        newBook = BooksDB.objects.create_book(request.POST, response[0].id, request.session['id'])
        if not newBook[0]:
            messages.error(request, newBook[1])
            return redirect('booksApp:add')
        ReviewsDB.objects.create_review(request.POST, newBook[0].id, request.session['id'])
    return redirect('booksApp:books')

def bookReview(request, id):
    context = {
        'book': BooksDB.objects.get(id=id),
        'reviews': ReviewsDB.objects.filter(book__id=id)
    }
    return render(request, 'booksApp/bookspage.html', context)


def addReview(request, id):
    ReviewsDB.objects.create_review(request.POST, id, request.session['id'])
    return redirect('booksApp:bookReview', id)

def user(request, id):
    context = {
        'user': Users.objects.get(id=id),
        'books': BooksDB.objects.filter(user__id=id),
    }
    return render(request, 'booksApp/userpage.html', context)

def delete(request, id):
    ReviewsDB.objects.get(id=id).delete()
    return redirect('booksApp:books')

Python/django/belt_reviewer/apps/booksApp/templates/booksApp/addBook.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Book and Review</title>
  </head>
  <body>
    <a href="{% url 'logRegApp:logout' %}">Logout</a>
    <a href="{% url 'booksApp:books' %}">Home</a>
    <form action="{% url 'booksApp:addBook' %}" method="post">
      {% csrf_token %}
      <label for="title">Book Title: </label>
      <input type="text" name="title" value="">
      <br>
      <label for="author">Author:</label>
      <br>
      <label for="existing_author">Choose from the list:</label>
      <select name="existing_author">
        <option value="choose">Choose</option>
        {% for author in authors %}
        <option value="{{author.name}}">{{author.name}}</option>
        {% endfor %}
      </select>
      <br>
      <label for="add_author">Add New Author: </label>
      <input type="text" name="add_author" value="">
      <br>
      <label for="review">Review: </label>
      <br>
      <textarea name="review" rows="8" cols="80"></textarea>
      <br>
      <label for="rating">Rating: </label>
      <select name="rating">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <br>
      <button type="submit" name="add" value="addBook">Add Book and Review</button>
    </form>
    {% if messages %}
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
    {% endif %}
  </body>
</html>

Python/django/belt_reviewer/apps/booksApp/templates/booksApp/books.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Books Home</title>
  </head>
  <body>
    <a href="{% url 'logRegApp:logout' %}">Logout</a>
    <h4>Welcome, {{request.session.fName}}</h4>
    <a href="{% url 'booksApp:add' %}">Add Book and Review</a>
    <hr>
    {% for review in reviews %}
    <h4><a href="{% url 'booksApp:bookReview' review.book.id %}">{{review.book.title}}</a></h4>
    <p>Rating: {{review.rating}}</p>
    <p>{{review.book.author.name}}</p>
    <p><a href="{% url 'booksApp:user' review.user.id %}">{{review.user.fName}}:</a> {{review.review}}</p>
    <p>{{review.created_at}}</p>
    <hr>
    {% endfor %}
  </body>
</html>

Python/django/belt_reviewer/apps/booksApp/templates/booksApp/bookspage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Book and Review</title>
  </head>
  <body>
    <a href="{% url 'logRegApp:logout' %}">Logout</a>
    <a href="{% url 'booksApp:books' %}">Home</a>
    <h4>{{book.title}}</h4>
    <p>Author: {{book.author.name}}</p>
    <h4>Reviews:</h4>
    <hr>
    {% for review in reviews %}
    <p>Rating: {{review.rating}}</p>
    <p><a href="{% url 'booksApp:user' review.user.id %}">{{review.user.fName}}:</a> {{review.review}}</p>
    <p>{{review.created_at}}</p>
    {% if review.user.id == request.session.id %}
    <a href="{% url 'booksApp:delete' review.id %}">Delete this Review</a>
    {% endif %}
    <hr>
    {% endfor %}
    <form action="{% url 'booksApp:addReview' book.id %}" method="post">
      {% csrf_token %}
      <label for="addReview">Add a Review:</label>
      <br>
      <textarea name="review" rows="8" cols="80"></textarea>
      <br>
      <label for="rating">Rating: </label>
      <select name="rating">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>
      <br>
      <button type="submit" name="add" value="addReview">Add Book and Review</button>
    </form>
  </body>
</html>

Python/django/belt_reviewer/apps/booksApp/templates/booksApp/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Books Review</title>
  </head>
  <body>
    <h4>Register</h4>
    <form action="{% url 'logRegApp:log_reg' %}" method="post">
      {% csrf_token %}
      <label for="fName">First Name: </label>
      <input type="text" name="fName" value="">
      <br>
      <label for="lName">Last Name: </label>
      <input type="text" name="lName" value="">
      <br>
      <label for="email">Email: </label>
      <input type="email" name="email" value="">
      <br>
      <label for="psw">Password: </label>
      <input type="password" name="psw" value="">
      <br>
      <label for="confpsw">Confirm Password: </label>
      <input type="password" name="confpsw" value="">
      <br>
      <button type="submit" name="action" value="register">Register</button>
    </form>
    <h4>Login</h4>
    <form action="{% url 'logRegApp:log_reg' %}" method="post">
      {% csrf_token %}
      <label for="email">Email: </label>
      <input type="email" name="email" value="">
      <br>
      <label for="psw">Password: </label>
      <input type="password" name="psw" value="">
      <br>
      <button type="submit" name="action" value="login">Login</button>
    </form>
    {% if messages %}
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
    {% endif %}
  </body>
</html>

Python/django/belt_reviewer/apps/booksApp/templates/booksApp/userpage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <a href="{% url 'booksApp:books' %}">Home</a>
    <a href="{% url 'booksApp:add' %}">Add Book and Review</a>
    <a href="{% url 'logRegApp:logout' %}">Logout</a>
    <h4>User Alias: {{user.fName}}</h4>
    <p>Name: {{user.fName}}  {{user.lName}}</p>
    <p>Email: {{user.email}}</p>
    <p>Total Reviews: {{user.users_reviews.count}}</p>
    <h4>Posted Reviews on the Following Books:</h4>
    {% for book in books %}
    <p><a href="{% url 'booksApp:bookReview' book.id %}">{{book.title}}</a></p>
    {% endfor %}
  </body>
</html>